# Generated by Django 3.1.2 on 2021-10-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_topic_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='匿名', max_length=100, verbose_name='投稿者の名前'),
            preserve_default=False,
        ),
    ]
